### ISSUE TITLE
Calculations are incorrect

### ISSUE THREAD

**Issue by willbushie** [willbushie/IT-Calculator#1]
A note from the grading of sprint: 1
===============
Eg, 0001 + 0010 a 110
eg, 0110 to Decimal a 8
What is required formated for base 2 (number of digits)?

Correct formatting of outputs from the methods.

**Comment by NDJohnson711** [comment]
I can look back over the calculations and see what i had done wrong

**Comment by willbushie** [comment]
With this bug, it seems to affect the binary arithmetic part of the application. There are still some errors with the conversion part of the application, but for this issue, focus on the binary arithmetic part.

**Comment by willbushie** [comment]
Not sure if this issue is still very relevant. We have issues specifically dealing with the conversion portion of the application, and it appears this issue has been resolved. It doesn't appear that the arithmetic portion of the application has any blaring issues. 
A few more issues have been brought about through the recent updates, will close this issue and open a new issue regrading those issues.
